### ISSUE TITLE
Lecture 15 PDF - typo in Hold and Wait section

### ISSUE THREAD

**Issue by tiffanylui** [jzarnett/ece254#19]
Deadlock prevention -> Hold and wait, fourth paragraph has a typo.  The sentence says "In theory, a process might never start if one **ore** more of the resources it needs is always in use (so this is vulnerable to starvation)."

**Comment by jzarnett** [comment]
Thank you for finding this; fixed in commit 0bc6ad3c7e9ab7d58975e9e16b3785eacb6aee0a
