### ISSUE TITLE
Lecture 16 Notes Typo? "We assign each of the five chopsticks a number from 0 to 5" implies there are actually six chopsticks.

### ISSUE THREAD

**Issue by a2xia** [jzarnett/ece254#34]
At the bottom of Page 1 when discussing the Dining Philosopher's problem, it says that we "assign each of the five chopsticks a number from 0 to 5." I think that should read "from 0 to 4", since we have a "zeroth" chopstick.

**Comment by bkthomps** [comment]
Being fixed by pull request #37

**Comment by bkthomps** [comment]
Fixed. I suggest we close this PR @jzarnett
